(
    (export + (decl    +   (Num Num)))
    (export - (decl    -   (Num Num)))
    (export * (decl    *   (Num Num)))
    (export / (decl    /   (Num Num)))
    (export > (decl    >   (Num Num)))
    (export < (decl    <   (Num Num)))
    (export >=(decl    >=  (Num Num)))
    (export <=(decl    <=  (Num Num)))
)