(&
	(declare eq (Any Any)) (exp $eq)
	(declare not (Any)) (exp $not)
	(declare run (Any)) (exp $run)
	; any amount of args not implemented (declare & (...Any)) (export $list)
	; (declare list (...Any)) (exp $list)
	; compound types? (declare map (...(Any Any))) (exp $list)
	; (declare panic (...Any)) (exp $panic)
	; (declare warn (...Any)) (exp $warn)
	; (declare write (...Any)) (exp $write)
	(declare tostr (Any)) (exp tostr)
)