(&
	(declare + (Num Num)) (exp $+)
	(declare - (Num Num)) (exp $-)
	(declare * (Num Num)) (exp $*)
	(declare / (Num Num)) (exp $/)
	(declare > (Num Num)) (exp $>)
	(declare < (Num Num)) (exp $<)
	(declare <= (Num Num)) (exp $<=)
	(declare >= (Num Num)) (exp $>=)
)
