(&
	(declare + (Any Any)) (exp $+)
	(declare - (Any Any)) (exp $-)
	(declare * (Any Any)) (exp $*)
	(declare / (Any Any)) (exp $/)
	(declare > (Num Num)) (exp $>)
	(declare < (Num Num)) (exp $<)
	(declare <= (Num Num)) (exp $<=)
	(declare >= (Num Num)) (exp $>=)
)
